language: python
python:
  - "2.7"
  - "3.4"
  - "3.5"
  - "3.6"
env:
  - DJANGO_VERSION=1.11
  - DJANGO_VERSION=2.0
install:
  - pip install -q Django==$DJANGO_VERSION
  - pip install -q -r requirements-dev.txt
  - python setup.py install
script:
  - pylama --options pytest.ini
  - python -Wall runtests.py